Move fixed hostnames to strict whitelist.
golemfactory/ya-installer-resources pull request #3
Opened 2022-11-18 14:07 UTC by evik42

Fix wildcards to regex.

Fixes https://github.com/golemfactory/yagna/issues/2306.

2022-11-18 14:59 UTC, nieznanysprawiciel approved these changes

2022-11-21 10:47 UTC, pwalski requested changes

2022-11-21 10:47 UTC, pwalski commented on whitelist/strict.lst
> +docker.io
```suggestion
docker.io
hub.docker.com
```

2022-11-21 10:47 UTC, pwalski commented on whitelist/strict.lst
> +github.com
```suggestion
github.com
api.github.com
```

2022-11-21 10:47 UTC, pwalski commented on whitelist/strict.lst
> +docker.io
Docker's REST api is accessed through path /api, but giving access to `hub.docker.com` probably makes sense

2022-11-21 10:47 UTC, pwalski commented on whitelist/strict.lst
> +github.com
Probably we should give access to api as well

2022-11-21 10:52 UTC, pwalski commented on whitelist/strict.lst
> +docker.io
Actually just checked that `registry.hub.docker.com` is an old domain, and now everything can be accessed through `docker.io`

2022-11-21 13:17 UTC, pwalski approved these changes

2022-11-21 13:57 UTC, pwalski approved these changes

2022-11-21 14:21 UTC, merged